### ISSUE TITLE
TT vs. TC

### ISSUE THREAD

**Issue by woodwind-enr** [Akaflieg-Freiburg/enrouteText#13]
Enroute indicates the true course with the corresponding abbreviation on the display being TT (true track). At least to me "TC" (true course) seems to be more common.

**Comment by kebekus** [comment]
I looked it up … and the distinction between "course" and "track" does not seem 100% clear. In US English, there seems to be some understanding that "course" is "intended direction" (…this is what is in your flight execution plan) whereas "track" is "actual direction (…this is what you read off your compass, give and take some corrections). And so, I use "TC" on the flight planning page and "TT" on the main page…
