### ISSUE TITLE
Misspelling METRA, TAR

### ISSUE THREAD

**Issue by woodwind-enr** [Akaflieg-Freiburg/enrouteText#14]
I found some "METRA" instead of METAR and "TAR" instead of TAF in the English source text of enroute_de.ts.

I fixed these items, BUT: I reckon there may be an equally misspelled counterpart in the app code that should be corrected.

**Comment by woodwind-enr** [comment]
Also applies to the other language files.

**Comment by kebekus** [comment]
Fixed. Thank you.
